language: clojure
lein: 2.7.1
dist: trusty

env:
    global:
      - JAVA_OPTS="-XX:MaxPermSize=256m"
      - LOG_DIR=$HOME/log
      - BIN_DIR=$HOME/bin
      - LEIN_ROOT=1
      - CTIA_MAJOR_VERSION=1
      - COMPOSE_URI=https://github.com/docker/compose/releases/download/1.9.0
      - COMPOSE_BIN=$HOME/bin/docker-compose-1-9-0
      - COMPOSE_LOG=$HOME/log/docker-compose.log
      - CTIA_STORE_ES_DEFAULT_HOST=127.0.0.1
      - CTIA_STORE_ES_DEFAULT_INDEXNAME=elasticsearch
      - CTIA_STORE_ES_DEFAULT_CLUSTERNAME=elasticsearch
      - CTIA_HOOK_ES_HOST=127.0.0.1
      - CTIA_HOOK_ES_PORT=9200
      - CTIA_HOOK_ES_INDEXNAME=elasticsearch
      - CTIA_HOOK_REDIS_URI=redis://127.0.0.1:6379
      - secure: "xiEuZbq8HbSAKQDB2swFnkWt8nvIIzDsMmtdEZ9Nri8v7M4jbkEngeGMARa3HxkAjzMzSMgHHkqtcpQdBpPJzmqK+S1HzQHpFN1oaqexWjN+v0+iquN0KBM8Yse+JXF8fpZg5BKH+VEUY3rdgLvyLF1bKpEbc4WhuiNpA/218yV8RLiQRwqypmn/zgM8AppuNiqMg/Ejxuo3GOlFIowH0z3SvBrjjAQSbG7UCTtyS5zXNyhw3EQcgB+x4ctNviIGcE3SRRNhOk5ivX1dG7sFj0CK0mvOZroxfu04CRWS0HwVm68KuQwLCGUm9daW33cd8u6YdvpaaI5+4iYuL+O95nYhKrO73AY7uhOwvguZF8263px0iPcTlaMqAx/RHxLMGqk3WxLy7krAR3UXg6BroKJXxWCoCZYIieoLHKL3B2KetJWAUDfiyw2zvUoaSFTHZgt10Pv97GnISkmYEE3mdszyQuQLJC2q8ugTQwFNSV3o8snrAtmGUeuIziiVZgXoR4Wj9PufuhQ6vrkVjvEuiRc54h9lmEzxgxpU/C9Ql4S08oggXR3BtDcEiRTs3GECdz/0BlZSb/KQFPPXU9ehp8ZLKCG3MeK2BuvlE3eycoPqVRfy8//4cM9fCKpesKShxbsZskV412o0fcmHA5brNrUnuD5/Xgi/eW3uNkVJLjg="
      - secure: "Kskfepn3+P/7dtXvybio6bZ+9YL9G5/gkvpSuDulbkCtP2Ws/Z+KU+CGBXfbn09RgUmOPoIQtmzH06z++Oqa9ZQytSf1Qf+amM8KrPNtK5naUjJL1vI7hUMK8Z/8FvszkmbtY32jHeQjrF0lUroLcsFJzZOG4khzvl4atjyS5wNVrdxFA+7SNy3gTQd7X8J/V3+uXyFwtRod4swxWNDlMpSUfF85c7htXbfyj1qFFkREmb6nnww3fj6x6P9BumXhP83ENzrpHYZH2NeGTTvkqQeklooqeo51xKqH1t4gvR6qneJJKUx/Qqk1goBXCERgC8q1HjD91t2lnRr/Pyzrl4qFtI5NUagaUHUbSPmxeuajgGhGcm19q157pd6hcQ/rpZKaR7yjsYmT5XlZXrxwGqMgLYaQYvHAobIyiJoVXnfcU6Vo6H1U5+FuWQPMWifEwB9LJEatZmZ3cc8ktw+wUwWtJAuM4myJbLe+j53fOiLxYiRvxl9XvSkGn0kwADojgLDw8iEFW3IHcstw7uH6bBeiAi0htMLI5PuyvZ0KG7dejEJkB8eACPvJNMzERhFoSKDFXbDz2h8p1ayQcdk2XdSi+hecW8IixWOadgEManxwkzrxoVRrdBMuh/DOYEi4IvvTqwtiEqrUMLU+rZ8SzuO533dG+RhZIVPKEkz7WHs="

# Cache our Maven deps to be kind to clojars, github, docker images
cache:
    directories:
    - $HOME/bin
    - $HOME/.m2
    - $HOME/.cache/pip
jdk:
    # https://github.com/travis-ci/travis-ci/issues/5227
    - oraclejdk8

before_install:
    # ES5 needs this
    - sudo sysctl -w vm.max_map_count=262144
    # create log & bin dir if missing
    - mkdir -p $LOG_DIR
    - mkdir -p $BIN_DIR

    #https://github.com/travis-ci/travis-ci/issues/5227
    - echo "127.0.0.1 "`hostname` | sudo tee /etc/hosts

    # install docker-compose if not in cache
    - if [ ! -f $COMPOSE_BIN ]; then curl -L {$COMPOSE_URI}/docker-compose-`uname -s`-`uname -m` > $COMPOSE_BIN; fi
    - chmod +x $COMPOSE_BIN

# install any dependencies required
install:
    - source $HOME/.rvm/scripts/rvm
    - rvm use 2.2

before_script:
    - $COMPOSE_BIN -f containers/dev/docker-compose.yml up -d> $COMPOSE_LOG
    # Wait ES
    - until curl http://127.0.0.1:9200/; do sleep 1; done
    # Wait Kafka
    - until echo dump | nc 127.0.0.1 2181 | grep brokers; do sleep 1; done

services:
    - docker

script:
  - ./build/run-tests.sh && ./build/build.sh

notifications:
  email: false
  hipchat:
    rooms:
      - secure: "Ec3/ASBzCcC+oTDJOcsTb+h2MHSWMZP2PbgZTOvHuf8nOokMU2LUjQi6ptaeMQlESvLPGGp8/b+mOOAaLQI15BrK0M+FaUfBxElHvWMqR9MxpNyprgDvs+0koZn/A6Ewal/eMHFl3IP1afBikDEbQWQJnhOtvgKYDZdX5sya4H9kCdPw+kFnj2CcOGybnIGuGGyZ90pvOsEobW6sYDz3B799YBki1QGcQ+8y9x5icUDV1ZdvhLZj+IP++kATqxyqq4VadF7PgbiBbac0umviiSpqE/RsD5tcAbm1a+57qIrzW1ofLDndUdp56gACOVvpvem0AjSfX3AHj7gYylLRk1KlDquNy55Ue/WfxUwyR59gvvueFlz+lQYcIVV7HDsE6uxQe4AcEUQ1pRdsCEUnPAbOqtouHGyqVyjMv42GDbf5nuPdPLIVodRD8mGfS+NCERB0sl62VFvM/dkJEz2BrLdgqOELwA2qZIZqgbhVTjsG6sVAa7G5t88eByIDKQjZWxq491hKbxPPU46s5/QXEQGTIOr6E+/52E+aRxcKT4232k404Mhga9U7TxLdKT2/VSLYOKU8cVGWHo317e7eJvucWJTSJ90yuCEUM0kyRckwuygZVTxUgql6DXadFVtdAKuNt6ZQM+UNGtnUODwFc/ZZGgMnJEM84+3N1AXaAKU="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (%{build_url})'
