language: clojure
lein: 2.7.1
dist: trusty

env:
    global:
      - JAVA_OPTS="-XX:MaxPermSize=256m"
      - LOG_DIR=$HOME/log
      - BIN_DIR=$HOME/bin
      - LEIN_ROOT=1
      - CTIA_MAJOR_VERSION=1
      - COMPOSE_URI=https://github.com/docker/compose/releases/download/1.9.0
      - COMPOSE_BIN=$HOME/bin/docker-compose-1-9-0
      - COMPOSE_LOG=$HOME/log/docker-compose.log
      - CTIA_STORE_ES_DEFAULT_HOST=127.0.0.1
      - CTIA_STORE_ES_DEFAULT_INDEXNAME=elasticsearch
      - CTIA_STORE_ES_DEFAULT_CLUSTERNAME=elasticsearch
      - CTIA_HOOK_ES_HOST=127.0.0.1
      - CTIA_HOOK_ES_PORT=9200
      - CTIA_HOOK_ES_INDEXNAME=elasticsearch
      - CTIA_HOOK_REDIS_URI=redis://127.0.0.1:6379
      - secure: "Mb9ZqaR3swyk9DONS0dF2MnvvfVHZztKgKuiySUe0dW4SyTZeiJ7g8aKCw/fnX4FgN4mwTelsX118rbVuqG3oEoTynkOA7+h8j1HMG+bZPZfgneQP8v+qJ0kqcp7cO820RpJM8l6vDEU1IxUIvxOI7Tgy0sUAg0qr75LEDjRp9pH/Rccwd1wlCPY55Qv07yxYW+VwCiUR8OSUFBY38fm68SZWzKFM2QwxBgHDwpaJ2VuJtIch8QT2tMtGS8l6Np4YC3r4mFTq6smkeZ+t4fglcIVcAFx+HwtyRqRAioCuuARl6SxF0trvggkHrvMHhFWO33F7tAWpXg3iUo/k+lH9o3dwFoNXx4LAhs4Q081vfeTeUEjHZRLx4QuWZ+9+aAvuVBc/Q4wSGw0INaYxcQv84V3jvbUkXTUZzgPgLEeRebaROvW/HWdBQ+rAi5OZDMsyq9g6odj05qfjjeYN0q+n3Z2TQgHg2fyfSmL4MGNFQLIVqB89WLWsllc9m8bErrZRKAz0+hMXRnCOSQq7ThJA/ets5PKqcNOe93A28E+ExicMq1EFM86tskJB3fHVhZsoJdS5JZwUFFnYY/pGqcADI4vfII0KE1hnZLFO07yG2nPF2NnJa/z1gpUwxfURQoBqc/vX2JMqwnyj7s9HkA9CBH/Kx0xGR3KGF722/fBwLY="
      - secure: "gSL3aw4LaBJJjw0GUbzsajFI7wU4Pk7haKXKfj+xthkeGD0a3XnB2yr+DnZfPRpSEo4SyQZl2NGSwg/9J2BduGA51v6jsFfmGIVdafLkOfZpRU7YP7EeUuPyyGNMt6DZ/D6j4z6aVqMLUqJpWylrmc+i40oMZRe4Omt2bO43OC6eF1U77hNeir0BMyhTnU2WmtXGaHpsqc0ImMheyKMWk5pkvc9xmd4+h/zeP1+hKyS5eKZKF0+3XXfDGR3QL2E3qXm0+HwHpNn9Pb8lZ+mzin/iCFsZ7s6HNfzyzT5bKXE/9Msl73+povKUoSWcYZljja4/EsJmOgIPpqn/XyogLqOKp8yHoZ5IQJ6KwGA8MZ7l/JIGutNjUgz6R/1P+79gsvyQsg6qTRMWZsmKxkC9eLhI+nyFNIE/gP/LD0MSEL/FHQKsnhSbAw3vaIW5oSPZyl/4+5J0fINAm3eCtICMZjRkEBXqTAs+DPeruv29OBsrdJoXoZMRef86PEL7QQpZM5EujagndeUgi3Rt0RGOA0wgGNe7Hu2XA9vEV79ICkzhKCAuXrCw7Wv1wyDpzLgraJGQFoA9JZKsWjGm8vK9xUvFc77/1vwNfBBMrnV7YprLxWYpR0lzfzYGNrcDjlcvSyy6FJ/B/IhPRN7BDJ3/LdNS8BjnUXN0XU2mYmgCv3M="

# Cache our Maven deps to be kind to clojars, github, docker images
cache:
    directories:
    - $HOME/bin
    - $HOME/.m2
jdk:
    # https://github.com/travis-ci/travis-ci/issues/5227
    - oraclejdk8

before_install:
    # ES5 needs this
    - sudo sysctl -w vm.max_map_count=262144
    # create log & bin dir if missing
    - mkdir -p $LOG_DIR
    - mkdir -p $BIN_DIR

    #https://github.com/travis-ci/travis-ci/issues/5227
    - echo "127.0.0.1 "`hostname` | sudo tee /etc/hosts

    # install docker-compose if not in cache
    - if [ ! -f $COMPOSE_BIN ]; then curl -L {$COMPOSE_URI}/docker-compose-`uname -s`-`uname -m` > $COMPOSE_BIN; fi
    - chmod +x $COMPOSE_BIN

# install any dependencies required
install:
    - source $HOME/.rvm/scripts/rvm
    - rvm use 2.2
    - gem install deb-s3
    - which deb-s3

before_script:
    - $COMPOSE_BIN -f containers/dev/docker-compose.yml up -d> $COMPOSE_LOG
    # Wait ES
    - until curl http://127.0.0.1:9200/; do sleep 1; done

services:
    - docker

script:
  - ./build/run-tests.sh && ./build/debian-package.sh

notifications:
  hipchat:
    rooms:
      - secure: "R+T+E8PCPugLLAh02v0lgZv5XXQ5ziCyu0lVWzleISLgZK9sVh0LthhjE2WkGD883TINpQ5LshWSutcgItv+dM++dhcBqP3uRHNDbyuhA7onsV80+2YNMBOY7avIcQmsBp60rp37ilrj9gBSQerQiiCdVxi+d9rDKGQsIZOBPTNCgSkuT209Ququ+XFuREjGrDZwqUuOloQxGM3UOspkitK/9dm2sVFOUrToEQSjTVUSaiX+1ptuRrMi0D4rkLOg4gHhiG3v0/BASvqFlXOiVtCHHa7EQ3ml2CPxDMPDq0zzTE8PtHlTe8Ew5d6L4/JZ7F0xi/fl3uQZ0E1PehslpSClO58n6NXh7bkTjSNEGFVdZfW9czCj+Gj17nHGqba9sG2eCyKNQWw5gVbDBGXBJWLEtJXBboisN8MT+vj7keW8WdlA+FIM8PSqZTCinVEN6IjDWkp3juTavbYbzBmNTMeCRAhBMGzufr4Wp9Yd/TApSsqyAOKbo4uxmrlbra05PY+AYKKb9YncLgp7xbWpPRNmVY1UGtSaAAq24pbolzPz2f9spvAm+aCHKoiPYZXa430Vsk6q33Ip/iw++8+Pr8tKm9gNWSFUNa7l+R7l9hS9L+q+sf48tHSPsZTqDoDGwEBCZYOwyTPbZI6N6Xp3ZZ7Vt4fOZAqdJJRHGO7W0jw="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
      - "Build details: %{build_url}"
