language: clojure
lein: lein2
script: lein2 do clean, javac, test
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
# branches:
#     only:
#         - master
# services:
#     - elasticsearch
# notifications:
#   hipchat: [api token]@[room id or name]
