language: clojure
lein: lein2
script: lein2 with-profile dev,ci do clean, javac, test

# Cache our Maven deps to be kind to clojars
cache:
    directories:
    - $HOME/.m2
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8

before_install:
    - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb && sudo service elasticsearch restart

before_script:
    # Wait ES
    - until curl http://localhost:9200/; do sleep 1; done
    - until redis-cli ping; do sleep 1; done
services:
    - elasticsearch
    - redis-server
# notifications:
#   hipchat: [api token]@[room id or name]
env:
    global:
      - CTIA_STORE_ES_URI=http://127.0.0.1:9200
      - CTIA_STORE_ES_HOST=127.0.0.1
      - CTIA_STORE_ES_INDEXNAME=elasticsearch
      - CTIA_HOOK_ES_URI=http://127.0.0.1:9200
      - CTIA_HOOK_ES_INDEXNAME=elasticsearch
      - CTIA_HOOK_REDIS_URI=redis://127.0.0.1:6379
