language: clojure
lein: lein2
script: lein2 do clean, javac, test :all

# Cache our Maven deps to be kind to clojars
cache:
    directories:
    - $HOME/.m2
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
# branches:
#     only:
#         - master

before_install:
    - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.5.deb && sudo service elasticsearch restart

before_script:
    - cp test/resources/ctia-test.properties.ci resources/ctia-default.properties
    # Wait ES
    - until curl http://localhost:9200/; do sleep 1; done

#services:
#    - elasticsearch
# notifications:
#   hipchat: [api token]@[room id or name]
