name: GitHub Actions Benchmark

# TODO change to cron or push 
on:
  pull_request:

defaults:
  run:
    working-directory: ./current-branch

jobs:
  benchmark:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          path: current-branch
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('current-branch/project.clj') }}
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@e73bf2b6435244b2c9c5c226ae5022d91d0ce702
        with:
          lein: 2.9.4
            #- name: Docker
            #  run: |
            #    docker-compose -f containers/dev/docker-compose.yml up -d
            #    # Wait ES
            #    until curl http://127.0.0.1:9200/; do sleep 1; done
            #    # Wait Kafka
            #    until echo dump | nc 127.0.0.1 2181 | grep brokers; do sleep 1; done
      - run: pwd
      - run: ls
      - run: ls scripts
      - run: ./scripts/run-benchmarks.sh
      - run: |
          mkdir -p target/bench
          echo "test" > target/bench/test.edn
          ls target/bench
      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          retention-days: 30
          name: benchmark-results
          path: current-branch/target/bench/*.edn
      - name: Copy benchmark results to gh-pages
        working-directory: gh-pages
        run: |
          git config pull.ff only
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          for attempt in $( seq 0 5 )
          do
            git pull origin gh-pages:gh-pages
            git reset --hard
            mkdir -p bench
            ( set -x; cp ${GITHUB_WORKSPACE}/current-branch/target/bench/* bench || true )
            git add bench
            git status
            git commit --allow-empty -m "Upload benchmarks"
            ( set +e; git push )
            PUSH_STATUS=$?
            if [ $PUSH_STATUS -eq 0 ] ; then
              break
            fi
            if [ $attempt -eq 5]; then
              echo "Git push failed after 5 attempts"
              exit $PUSH_STATUS
            else
              echo "Git push failed, trying (attempt ${attempt})"
              git reset --hard HEAD~1
              # exponential backoff
              sleep $(( 2 ** $attempt + $( seq 0 10 | sort -R | head -n 1 )))
            fi
          done
