name: Clojure CI

on:
  pull_request:

env:
  LOG_DIR: ~/log
  BIN_DIR: ~/bin
  LEIN_ROOT: 1
  CTIA_MAJOR_VERSION: 1
  COMPOSE_URI: https://github.com/docker/compose/releases/download/1.9.0
  COMPOSE_BIN: ~/bin/docker-compose-1-9-0
  COMPOSE_LOG: ~/log/docker-compose.log
  CTIA_STORE_ES_DEFAULT_HOST: 127.0.0.1
  CTIA_STORE_ES_DEFAULT_INDEXNAME: elasticsearch
  CTIA_STORE_ES_DEFAULT_CLUSTERNAME: elasticsearch
  CTIA_HOOK_ES_HOST: 127.0.0.1
  CTIA_HOOK_ES_PORT: 9200
  CTIA_HOOK_ES_INDEXNAME: elasticsearch
  CTIA_HOOK_REDIS_URI: redis://127.0.0.1:6379
  CTIA_NSPLITS: 15 # number of matrix builds
  SHELLCHECK_VERSION: "v0.7.0" # "stable" or "v0.4.7", or "latest"

jobs:
  ## TODO fan in and deploy
  # deploy:
  #   needs: test
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        this-split: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14] # (range ${CTIA_NSPLITS})
    env:
      CTIA_THIS_SPLIT: ${{ matrix.this-split }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.4
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/bin
            ~/.m2
            ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('project.clj') }}

      - name: Setup folders
        run: |
          mkdir -p ~/bin
          mkdir -p ~/log

      - name: ES5 setup
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Create log dir if missing
        run: mkdir -p $LOG_DIR

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Docker
        run: |
          docker-compose -f containers/dev/docker-compose.yml up -d > $COMPOSE_LOG
          # Wait ES
          until curl http://127.0.0.1:9200/; do sleep 1; done
          # Wait Kafka
          until echo dump | nc 127.0.0.1 2181 | grep brokers; do sleep 1; done

      - run: ./build/run-tests.sh
